[mypy]
python_version = 3.12
warn_unused_configs = True

[mypy-setuptools.*]
ignore_missing_imports = True

ignore_missing_imports = True

ignore_missing_imports = True

ignore_missing_imports = True

ignore_missing_imports = True

ignore_missing_imports = True

[mypy-tests]
ignore_errors = True
